version: '3.8'
services:
  db:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
      
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: mypass123
      MARIADB_DATABASE: crawlerdb
      MARIADB_USER: example
      MARIADB_PASSWORD: example
    ports:
      - "13306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    hostname: db

  phpmyadmin:

    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80  
    hostname: phpmyadmin
  #carrerjet:
   #build:
     #context: ./careerjet
      #dockerfile: Dockerfile
  careernet:
    build:
      context: ./careernet
      dockerfile: Dockerfile
    hostname: careernet
    container_name: careernet1
    depends_on:
      - db
    restart: on-failure
    
   
  #indeedgr:
  #jobfind:
  #jooble:
  #kariera:
  randstand:
    build:
      context: ./randstad
      dockerfile: Dockerfile
    hostname: randstad
    container_name: randstad
    depends_on:
      - db
    #command: 
    restart: on-failure
    
  #skywalker:
    #build:
      #context: ./skywalker
      #dockerfile: skywalker.dockerfile
volumes:
  dbdata:
  

